### ISSUE TITLE
Ajouter un filtre pour occurences de cours de soir

### ISSUE THREAD

**Issue by samdidos** [Krystosterone/ets-horaire-website#3]
Salut, ça serait cool s'il pouvait y avoir un filtre pour le nombre de cours qu'on accepterait à avoir de soir. Par exemple, dans mon cas, je n'ai pas de préférences par rapport à quel soir de la semaine sera dédié à mes cours, mais j'en voudrais maximum 2 par semaine. Ça pourrait être fait pour les autres périodes, mais je pense que le besoin serait surtout pour le soir.

Sinon beau travail! Le site est clean et c'est pratique. Je te suggère de soumettre ton projet à la Maison du Logiciel Libre qui ouvre bientôt, où des étudiants de l'ETS vont apprendre à contribuer à des projets libres.  http://maisonlogiciellibre.org/

**Comment by gnut3ll4** [comment]
Salut Krystian, comme le suggère @samdidos, la maison du logiciel libre est une très belle opportunité! Tu peux créer des missions pour ton projet auxquelles tout le monde peut participer pour bénéficier d'une visibilité tout en contribuant pour la communauté! :smile:

**Comment by Krystosterone** [comment]
@samdidos @gnut3ll4 Merci pour le billet!
Malheureusement, depuis janvier, j'ai re-codé au grand complet le site et suis encore en train de débattre si je devrais le rendre disponible à tous sous la licence se logiciel libre.

J'ai copié le billet dans mon repo privé et je vais garder l'idée en tête. Merci à vous

**Comment by Krystosterone** [comment]
Bougé ici: https://github.com/Krystosterone/rubik/issues/8
